server:
  port: 8080
spring:
  application:
    name: TokenGenerator
jwt:
  secret: N3t4mX7E4QkgN6SX5e1Px7j8HMGsyGVK68775bPQqhkqLrPqN36iNBpv4VLPWfcGf6dhm1nRNmdM1xu3M19smTYj34JV5GPFMCi19XFVZ9kfibYhNk7j58KCLKB3C5P6
  expiration: 3600000
  type: JWT
